### ISSUE TITLE
Pass in .ansible-lint configuration file

### ISSUE THREAD

**Issue by Mazelt** [sbaudoin/sonar-ansible#12]
Hi,

we have an .ansible-lint configuration inside the root directory of our projects.
As the plugin does run ansible-lint on each file seperately the .ansible-lint config is not used for playbooks in subdirectories.

A great feature would be to be able to configure the path to .ansible-lint and have it passed to ansible-lint via the `-c` flag.

Thanks,
Mazelt

**Comment by greenflowers** [comment]
That would indeed be very useful for global exclusion of rules. Per default the file should reside in the basepath of the directory. See https://github.com/geerlingguy/ansible-role-sonar as an example.

**Comment by sbaudoin** [comment]
That's a good feature, I'll implement it hopefully shortly

**Comment by greenflowers** [comment]
That would be terrific. I would offer my help, but my Java skills are super rusty.

**Comment by sbaudoin** [comment]
Version 2.2.0 released.

**Comment by greenflowers** [comment]
Thank you, I will test that and report back!
