### ISSUE TITLE
INFO: No active rules found for this plugin

### ISSUE THREAD

**Issue by huornlmj** [sbaudoin/sonar-ansible#16]
Scans are not showing any Ansible related content on the SonarQube server.

SonarQube server v 7.9
sonar-scanner v 4.0.0.1744
Ansible-lint v 4.1.0

A new quality profile was created on the server like so:

- SonarQube 'Quality profiles' menu
- Click 'Create'
- Name: Ansible
- Language: YAML
- Parent: Sonar way (built-in)
- Click 'Activate more'
- Search in 'tag' for 'ansible'
- Click 'Bulk change'
- Activate in Ansible
- (60 rules activated)

Then run sonar-scanner on machine with Ansible YAML files, sonar-scanner and ansible-lint:

INFO: 28 files indexed
INFO: 0 files ignored because of scm ignore settings
INFO: Quality profile for py: Sonar way
INFO: Quality profile for yaml: Sonar way
...
INFO: Sensor Ansible Lint Sensor [ansible]
INFO: No active rules found for this plugin, skipping.
INFO: Sensor Ansible Lint Sensor [ansible] (done) | time=1ms
...
INFO: Sensor YAML Sensor [yaml]
WARN: Metric 'comment_lines_data' is deprecated. Provided value is ignored.
INFO: Sensor YAML Sensor [yaml] (done) | time=843ms
...
INFO: ANALYSIS SUCCESSFUL, you can browse <REDACTED>

**Comment by sbaudoin** [comment]
Hello,

Thanks for the details, this is a well documented ticket ;)

From your configuration and the scanner output, I'd say that you did not set your Ansible profile as default or did no assign it to your project. As a consequence, SonarQube uses the default profile (Sonar way) that is pure YAML and has no Ansible rules, which explains the message "No active rules found for this plugin, skipping.".

**Comment by pbolle** [comment]
Hi @sbaudoin,

I have exectly the same problem "INFO: No active rules found for this plugin, skipping". 
Can you give me a hint how to set Ansible profile as default.
I was hoping to find it here https://github.com/sbaudoin/sonar-ansible/tree/master/it.
