### ISSUE TITLE
5.0.6 not work

### ISSUE THREAD

**Issue by chris93111** [sbaudoin/sonar-ansible#33]
hello 

With ansible-lint 5.0.6 they are many error with analysis

WARNING  Listing 43 violation(s) that are fatal
WARN: Invalid issue syntax, ignoring: ../../playbook/test.yml:8: risky-shell-pipe
WARN: Errors happened during analysis:

**Comment by sbaudoin** [comment]
Looks like it is due to #34

**Comment by sbaudoin** [comment]
So yes, I confirm this is due to #34. The bottom line is that the rules have new ids so it should just be a matter of adding new rules. I close the issue as a duplicate of #34.
