### ISSUE TITLE
Starting with ansible-lint 5.0.x format of output changed

### ISSUE THREAD

**Issue by chrisrohr** [sbaudoin/sonar-ansible#34]
Hey there,

I wanted to add a ticket here as I noticed that starting with this commit (https://github.com/ansible-community/ansible-lint/pull/1305) on ansible-lint, they removed the E### rule id and replaced them all with text based ids.  This will obviously break the link to sonar.  If someone could point me in the right direction, I could try to provide a PR to address this.

This will probably be a little bit harder to stay backwards compatible like you did with the ANSIBLE##### to E### transition so not sure if you would want this as a breaking change or not.

**Comment by sbaudoin** [comment]
Hello,

Thanks for reporting the issue. I'll have a look a this.

**Comment by sbaudoin** [comment]
ansible-lint keeps on changing the output format, this is really a pain: 5.0.0 to 5.0.2 had the "new" syntax "error_id file:line", but starting from 5.0.3 this is the old syntax "file:line: error_id"...

Anyway, adding the new rules should be sufficient to fix the problem.

**Comment by chrisrohr** [comment]
Thank you for checking on this.  Please let me know if you want me to try to submit a PR for it.
