### ISSUE TITLE
Ansible-lint recommend version

### ISSUE THREAD

**Issue by pedrooct** [sbaudoin/sonar-ansible#39]
Hi!

Sorry if this was already address, but what version do you recomend for ansible-lint?

Thank you.

**Comment by sbaudoin** [comment]
Hello,

So far, ansible-lint 3.4 up to 4.3.7 (the latest 4 release) are supported. Version 5 is not supported yet: I'm working on that, so the next release of the plugin will hopefully support the 5.x releases.

Please note that although a version of ansible-lint is supported, some "odd" behavior may occur. This is the case with the early releases of 4.3 and 5.0, for which undesired warnings will be reported in the scanner's log but without causing any problem in issue handling.

**Comment by pedrooct** [comment]
Thank you for the quick response.
