### ISSUE TITLE
Compatibility with Sonar v9.2

### ISSUE THREAD

**Issue by ramarns** [sbaudoin/sonar-ansible#47]
Hello Team,

We have observed that latest Sonar lint plugin version: 2.5.0 would not be supported SonarQube v9.2.

https://docs.sonarqube.org/latest/instance-administration/plugin-version-matrix/

Would be great help, if you could provide some updates on the latest SonarQube supports with this plugin.

Thanks.

**Comment by sbaudoin** [comment]
Hello,

I'm going to test. There is no reason why it would not be. If it is OK, I'll see with SQ how to update the marketplace.

**Comment by sbaudoin** [comment]
I just released version 2.5.1 with official support for SonarQube 9.2 (without significant code change, so version 2.5.0 also works on SonarQube 9.2). Please grant some time before it is available in the marketplace. You can manually deploy this 2.5.1 version in the meantime if you are in a rush.
