### ISSUE TITLE
Ansible lint not sending complete report to Sonarqube

### ISSUE THREAD

**Issue by Sandeeparch** [sbaudoin/sonar-ansible#48]
Thanks for the plugin
Having Issues on sending the report to Sonarqube:

Is there any exception that this plugin will send only specific code in sonarqube.

Because when I run the linting locally I'm getting lot of errors which are not showing in the sonarqube. 

Could you pls help me by providing how the interation between Sonarqube and linting works. please let me know any more details.

Thanks in Advance.

**Comment by sbaudoin** [comment]
Hello,

Please can you provide more details about the issue you are facing, please?
- Version of ansible-lint you are using
- A ZIP file with a sample of the files you use
- The commands you execute to produce the errors with the sample files and that are not saved in SQ

Also make sure you have enabled all the rules in SQ: by default there is no rule enabled.

Thanks

**Comment by Sandeeparch** [comment]
Hello,
Thanks for response, we updated YAML and ansbile version in sonarqube issue got resolved. Please find the updated details below. 

Prev Version
ansible-lint 2.4.0 & yaml 1.6.0

Updated To
ansible-lint 2.5.1 & yaml 1.7.0

Since the issue is resolved we are closing in github. Thanks again .
